"""add bookings

Revision ID: 078e8784a5f4
Revises: 12ee28f76d24
Create Date: 2025-07-06 22:40:07.110852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '078e8784a5f4'
down_revision: Union[str, None] = '12ee28f76d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_in',
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bookings', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_in_agency'), 'book_in', ['agency'], unique=False)
    op.create_index(op.f('ix_book_in_bookings'), 'book_in', ['bookings'], unique=False)
    op.create_index(op.f('ix_book_in_created_at'), 'book_in', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_in_incomplete'), 'book_in', ['incomplete'], unique=False)
    op.create_index(op.f('ix_book_in_range'), 'book_in', ['range'], unique=False)
    op.create_index(op.f('ix_book_in_report_id'), 'book_in', ['report_id'], unique=False)
    op.create_index(op.f('ix_book_in_started'), 'book_in', ['started'], unique=False)
    op.create_index(op.f('ix_book_in_timestamp'), 'book_in', ['timestamp'], unique=False)
    op.create_index(op.f('ix_book_in_uuid'), 'book_in', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_in_uuid'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_timestamp'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_started'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_report_id'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_range'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_incomplete'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_created_at'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_bookings'), table_name='book_in')
    op.drop_index(op.f('ix_book_in_agency'), table_name='book_in')
    op.drop_table('book_in')
    # ### end Alembic commands ###
