"""add releases and processing disposition

Revision ID: 0fb976c024d7
Revises: 2ebb8b841c23
Create Date: 2025-07-06 02:44:35.110126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fb976c024d7'
down_revision: Union[str, None] = '2ebb8b841c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_disposition',
    sa.Column('disposition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_disposition_created_at'), 'processing_disposition', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_disposition_disposition'), 'processing_disposition', ['disposition'], unique=False)
    op.create_index(op.f('ix_processing_disposition_facility'), 'processing_disposition', ['facility'], unique=False)
    op.create_index(op.f('ix_processing_disposition_population'), 'processing_disposition', ['population'], unique=False)
    op.create_index(op.f('ix_processing_disposition_report_id'), 'processing_disposition', ['report_id'], unique=False)
    op.create_index(op.f('ix_processing_disposition_uuid'), 'processing_disposition', ['uuid'], unique=True)
    op.create_table('release',
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criminality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('releases', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_created_at'), 'release', ['created_at'], unique=False)
    op.create_index(op.f('ix_release_criminality'), 'release', ['criminality'], unique=False)
    op.create_index(op.f('ix_release_incomplete'), 'release', ['incomplete'], unique=False)
    op.create_index(op.f('ix_release_range'), 'release', ['range'], unique=False)
    op.create_index(op.f('ix_release_reason'), 'release', ['reason'], unique=False)
    op.create_index(op.f('ix_release_releases'), 'release', ['releases'], unique=False)
    op.create_index(op.f('ix_release_report_id'), 'release', ['report_id'], unique=False)
    op.create_index(op.f('ix_release_started'), 'release', ['started'], unique=False)
    op.create_index(op.f('ix_release_timestamp'), 'release', ['timestamp'], unique=False)
    op.create_index(op.f('ix_release_uuid'), 'release', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_uuid'), table_name='release')
    op.drop_index(op.f('ix_release_timestamp'), table_name='release')
    op.drop_index(op.f('ix_release_started'), table_name='release')
    op.drop_index(op.f('ix_release_report_id'), table_name='release')
    op.drop_index(op.f('ix_release_releases'), table_name='release')
    op.drop_index(op.f('ix_release_reason'), table_name='release')
    op.drop_index(op.f('ix_release_range'), table_name='release')
    op.drop_index(op.f('ix_release_incomplete'), table_name='release')
    op.drop_index(op.f('ix_release_criminality'), table_name='release')
    op.drop_index(op.f('ix_release_created_at'), table_name='release')
    op.drop_table('release')
    op.drop_index(op.f('ix_processing_disposition_uuid'), table_name='processing_disposition')
    op.drop_index(op.f('ix_processing_disposition_report_id'), table_name='processing_disposition')
    op.drop_index(op.f('ix_processing_disposition_population'), table_name='processing_disposition')
    op.drop_index(op.f('ix_processing_disposition_facility'), table_name='processing_disposition')
    op.drop_index(op.f('ix_processing_disposition_disposition'), table_name='processing_disposition')
    op.drop_index(op.f('ix_processing_disposition_created_at'), table_name='processing_disposition')
    op.drop_table('processing_disposition')
    # ### end Alembic commands ###
