"""add releases and processing disposition

Revision ID: 12ee28f76d24
Revises: 0fb976c024d7
Create Date: 2025-07-06 05:48:40.937186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ee28f76d24'
down_revision: Union[str, None] = '0fb976c024d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_out_release',
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criminality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('releases', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_out_release_created_at'), 'book_out_release', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_out_release_criminality'), 'book_out_release', ['criminality'], unique=False)
    op.create_index(op.f('ix_book_out_release_incomplete'), 'book_out_release', ['incomplete'], unique=False)
    op.create_index(op.f('ix_book_out_release_range'), 'book_out_release', ['range'], unique=False)
    op.create_index(op.f('ix_book_out_release_reason'), 'book_out_release', ['reason'], unique=False)
    op.create_index(op.f('ix_book_out_release_releases'), 'book_out_release', ['releases'], unique=False)
    op.create_index(op.f('ix_book_out_release_report_id'), 'book_out_release', ['report_id'], unique=False)
    op.create_index(op.f('ix_book_out_release_started'), 'book_out_release', ['started'], unique=False)
    op.create_index(op.f('ix_book_out_release_timestamp'), 'book_out_release', ['timestamp'], unique=False)
    op.create_index(op.f('ix_book_out_release_uuid'), 'book_out_release', ['uuid'], unique=True)
    op.drop_index(op.f('ix_release_created_at'), table_name='release')
    op.drop_index(op.f('ix_release_criminality'), table_name='release')
    op.drop_index(op.f('ix_release_incomplete'), table_name='release')
    op.drop_index(op.f('ix_release_range'), table_name='release')
    op.drop_index(op.f('ix_release_reason'), table_name='release')
    op.drop_index(op.f('ix_release_releases'), table_name='release')
    op.drop_index(op.f('ix_release_report_id'), table_name='release')
    op.drop_index(op.f('ix_release_started'), table_name='release')
    op.drop_index(op.f('ix_release_timestamp'), table_name='release')
    op.drop_index(op.f('ix_release_uuid'), table_name='release')
    op.drop_table('release')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('incomplete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('started', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('criminality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('releases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], name=op.f('release_report_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('release_pkey'))
    )
    op.create_index(op.f('ix_release_uuid'), 'release', ['uuid'], unique=True)
    op.create_index(op.f('ix_release_timestamp'), 'release', ['timestamp'], unique=False)
    op.create_index(op.f('ix_release_started'), 'release', ['started'], unique=False)
    op.create_index(op.f('ix_release_report_id'), 'release', ['report_id'], unique=False)
    op.create_index(op.f('ix_release_releases'), 'release', ['releases'], unique=False)
    op.create_index(op.f('ix_release_reason'), 'release', ['reason'], unique=False)
    op.create_index(op.f('ix_release_range'), 'release', ['range'], unique=False)
    op.create_index(op.f('ix_release_incomplete'), 'release', ['incomplete'], unique=False)
    op.create_index(op.f('ix_release_criminality'), 'release', ['criminality'], unique=False)
    op.create_index(op.f('ix_release_created_at'), 'release', ['created_at'], unique=False)
    op.drop_index(op.f('ix_book_out_release_uuid'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_timestamp'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_started'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_report_id'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_releases'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_reason'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_range'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_incomplete'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_criminality'), table_name='book_out_release')
    op.drop_index(op.f('ix_book_out_release_created_at'), table_name='book_out_release')
    op.drop_table('book_out_release')
    # ### end Alembic commands ###
