"""facilities

Revision ID: 2686878943cb
Revises: 84632fb9fb1f
Create Date: 2025-07-12 16:06:41.868180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2686878943cb'
down_revision: Union[str, None] = '84632fb9fb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_detailed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fy25_alos', sa.Float(), nullable=True),
    sa.Column('level_a', sa.Float(), nullable=True),
    sa.Column('level_b', sa.Float(), nullable=True),
    sa.Column('level_c', sa.Float(), nullable=True),
    sa.Column('level_d', sa.Float(), nullable=True),
    sa.Column('male_crim', sa.Float(), nullable=True),
    sa.Column('male_non_crim', sa.Float(), nullable=True),
    sa.Column('female_crim', sa.Float(), nullable=True),
    sa.Column('female_non_crim', sa.Float(), nullable=True),
    sa.Column('ice_threat_level_1', sa.Float(), nullable=True),
    sa.Column('ice_threat_level_2', sa.Float(), nullable=True),
    sa.Column('ice_threat_level_3', sa.Float(), nullable=True),
    sa.Column('no_ice_threat_level', sa.Float(), nullable=True),
    sa.Column('mandatory', sa.Float(), nullable=True),
    sa.Column('guaranteed_minimum', sa.Float(), nullable=True),
    sa.Column('last_inspection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_inspection_end_date', sa.DateTime(), nullable=True),
    sa.Column('pending_fy25_inspection', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_inspection_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_final_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_address'), 'facilities', ['address'], unique=False)
    op.create_index(op.f('ix_facilities_aor'), 'facilities', ['aor'], unique=False)
    op.create_index(op.f('ix_facilities_city'), 'facilities', ['city'], unique=False)
    op.create_index(op.f('ix_facilities_created_at'), 'facilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_facilities_female_crim'), 'facilities', ['female_crim'], unique=False)
    op.create_index(op.f('ix_facilities_female_non_crim'), 'facilities', ['female_non_crim'], unique=False)
    op.create_index(op.f('ix_facilities_fy25_alos'), 'facilities', ['fy25_alos'], unique=False)
    op.create_index(op.f('ix_facilities_gender'), 'facilities', ['gender'], unique=False)
    op.create_index(op.f('ix_facilities_guaranteed_minimum'), 'facilities', ['guaranteed_minimum'], unique=False)
    op.create_index(op.f('ix_facilities_ice_threat_level_1'), 'facilities', ['ice_threat_level_1'], unique=False)
    op.create_index(op.f('ix_facilities_ice_threat_level_2'), 'facilities', ['ice_threat_level_2'], unique=False)
    op.create_index(op.f('ix_facilities_ice_threat_level_3'), 'facilities', ['ice_threat_level_3'], unique=False)
    op.create_index(op.f('ix_facilities_last_final_rating'), 'facilities', ['last_final_rating'], unique=False)
    op.create_index(op.f('ix_facilities_last_inspection_end_date'), 'facilities', ['last_inspection_end_date'], unique=False)
    op.create_index(op.f('ix_facilities_last_inspection_standard'), 'facilities', ['last_inspection_standard'], unique=False)
    op.create_index(op.f('ix_facilities_last_inspection_type'), 'facilities', ['last_inspection_type'], unique=False)
    op.create_index(op.f('ix_facilities_level_a'), 'facilities', ['level_a'], unique=False)
    op.create_index(op.f('ix_facilities_level_b'), 'facilities', ['level_b'], unique=False)
    op.create_index(op.f('ix_facilities_level_c'), 'facilities', ['level_c'], unique=False)
    op.create_index(op.f('ix_facilities_level_d'), 'facilities', ['level_d'], unique=False)
    op.create_index(op.f('ix_facilities_male_crim'), 'facilities', ['male_crim'], unique=False)
    op.create_index(op.f('ix_facilities_male_non_crim'), 'facilities', ['male_non_crim'], unique=False)
    op.create_index(op.f('ix_facilities_mandatory'), 'facilities', ['mandatory'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_index(op.f('ix_facilities_no_ice_threat_level'), 'facilities', ['no_ice_threat_level'], unique=False)
    op.create_index(op.f('ix_facilities_pending_fy25_inspection'), 'facilities', ['pending_fy25_inspection'], unique=False)
    op.create_index(op.f('ix_facilities_report_id'), 'facilities', ['report_id'], unique=False)
    op.create_index(op.f('ix_facilities_state'), 'facilities', ['state'], unique=False)
    op.create_index(op.f('ix_facilities_type_detailed'), 'facilities', ['type_detailed'], unique=False)
    op.create_index(op.f('ix_facilities_uuid'), 'facilities', ['uuid'], unique=True)
    op.create_index(op.f('ix_facilities_zip_code'), 'facilities', ['zip_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_zip_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_uuid'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_type_detailed'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_state'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_report_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_pending_fy25_inspection'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_no_ice_threat_level'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_mandatory'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_male_non_crim'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_male_crim'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_level_d'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_level_c'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_level_b'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_level_a'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_last_inspection_type'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_last_inspection_standard'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_last_inspection_end_date'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_last_final_rating'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_ice_threat_level_3'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_ice_threat_level_2'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_ice_threat_level_1'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_guaranteed_minimum'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_gender'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_fy25_alos'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_female_non_crim'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_female_crim'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_created_at'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_city'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_aor'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_address'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
