"""add avg stay

Revision ID: 2ebb8b841c23
Revises: f959a421fc58
Create Date: 2025-07-05 22:04:01.694982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ebb8b841c23'
down_revision: Union[str, None] = 'f959a421fc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('average_stay_length', sa.Column('length_of_stay', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_average_stay_length_population'), table_name='average_stay_length')
    op.create_index(op.f('ix_average_stay_length_length_of_stay'), 'average_stay_length', ['length_of_stay'], unique=False)
    op.drop_column('average_stay_length', 'population')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('average_stay_length', sa.Column('population', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_average_stay_length_length_of_stay'), table_name='average_stay_length')
    op.create_index(op.f('ix_average_stay_length_population'), 'average_stay_length', ['population'], unique=False)
    op.drop_column('average_stay_length', 'length_of_stay')
    # ### end Alembic commands ###
