"""added experiences

Revision ID: 5a69e4ac22fa
Revises: a62c2b5bfa15
Create Date: 2025-07-24 08:18:18.130621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a69e4ac22fa'
down_revision: Union[str, None] = 'a62c2b5bfa15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detainment_experiences',
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detainment_experiences_created_at'), 'detainment_experiences', ['created_at'], unique=False)
    op.create_index(op.f('ix_detainment_experiences_reported_at'), 'detainment_experiences', ['reported_at'], unique=False)
    op.create_index(op.f('ix_detainment_experiences_source_name'), 'detainment_experiences', ['source_name'], unique=False)
    op.create_index(op.f('ix_detainment_experiences_updated_at'), 'detainment_experiences', ['updated_at'], unique=False)
    op.create_index(op.f('ix_detainment_experiences_uuid'), 'detainment_experiences', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detainment_experiences_uuid'), table_name='detainment_experiences')
    op.drop_index(op.f('ix_detainment_experiences_updated_at'), table_name='detainment_experiences')
    op.drop_index(op.f('ix_detainment_experiences_source_name'), table_name='detainment_experiences')
    op.drop_index(op.f('ix_detainment_experiences_reported_at'), table_name='detainment_experiences')
    op.drop_index(op.f('ix_detainment_experiences_created_at'), table_name='detainment_experiences')
    op.drop_table('detainment_experiences')
    # ### end Alembic commands ###
