"""add avg daily pop

Revision ID: 8eaf8d647259
Revises: 80f0180dc176
Create Date: 2025-07-05 21:25:49.809172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8eaf8d647259'
down_revision: Union[str, None] = '80f0180dc176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detention_stats_reports',
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('publication_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=False),
    sa.Column('raw_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detention_stats_reports_created_at'), 'detention_stats_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_fiscal_year'), 'detention_stats_reports', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_hidden'), 'detention_stats_reports', ['hidden'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_publication_date'), 'detention_stats_reports', ['publication_date'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_publication_month'), 'detention_stats_reports', ['publication_month'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_publication_year'), 'detention_stats_reports', ['publication_year'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_source_name'), 'detention_stats_reports', ['source_name'], unique=False)
    op.create_index(op.f('ix_detention_stats_reports_uuid'), 'detention_stats_reports', ['uuid'], unique=True)
    op.create_table('average_daily_population',
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criminality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_average_daily_population_agency'), 'average_daily_population', ['agency'], unique=False)
    op.create_index(op.f('ix_average_daily_population_created_at'), 'average_daily_population', ['created_at'], unique=False)
    op.create_index(op.f('ix_average_daily_population_criminality'), 'average_daily_population', ['criminality'], unique=False)
    op.create_index(op.f('ix_average_daily_population_incomplete'), 'average_daily_population', ['incomplete'], unique=False)
    op.create_index(op.f('ix_average_daily_population_population'), 'average_daily_population', ['population'], unique=False)
    op.create_index(op.f('ix_average_daily_population_range'), 'average_daily_population', ['range'], unique=False)
    op.create_index(op.f('ix_average_daily_population_report_id'), 'average_daily_population', ['report_id'], unique=False)
    op.create_index(op.f('ix_average_daily_population_started'), 'average_daily_population', ['started'], unique=False)
    op.create_index(op.f('ix_average_daily_population_timestamp'), 'average_daily_population', ['timestamp'], unique=False)
    op.create_index(op.f('ix_average_daily_population_uuid'), 'average_daily_population', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_average_daily_population_uuid'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_timestamp'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_started'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_report_id'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_range'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_population'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_incomplete'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_criminality'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_created_at'), table_name='average_daily_population')
    op.drop_index(op.f('ix_average_daily_population_agency'), table_name='average_daily_population')
    op.drop_table('average_daily_population')
    op.drop_index(op.f('ix_detention_stats_reports_uuid'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_source_name'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_publication_year'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_publication_month'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_publication_date'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_hidden'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_fiscal_year'), table_name='detention_stats_reports')
    op.drop_index(op.f('ix_detention_stats_reports_created_at'), table_name='detention_stats_reports')
    op.drop_table('detention_stats_reports')
    # ### end Alembic commands ###
