"""facilities

Revision ID: a62c2b5bfa15
Revises: 2686878943cb
Create Date: 2025-07-12 16:29:43.874338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a62c2b5bfa15'
down_revision: Union[str, None] = '2686878943cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('facilities', 'fy25_alos',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'fy25_alos',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('facilities', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
