"""add avg stay

Revision ID: f959a421fc58
Revises: 8eaf8d647259
Create Date: 2025-07-05 22:01:08.929948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f959a421fc58'
down_revision: Union[str, None] = '8eaf8d647259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_stay_length',
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criminality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('population', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['detention_stats_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_average_stay_length_agency'), 'average_stay_length', ['agency'], unique=False)
    op.create_index(op.f('ix_average_stay_length_created_at'), 'average_stay_length', ['created_at'], unique=False)
    op.create_index(op.f('ix_average_stay_length_criminality'), 'average_stay_length', ['criminality'], unique=False)
    op.create_index(op.f('ix_average_stay_length_incomplete'), 'average_stay_length', ['incomplete'], unique=False)
    op.create_index(op.f('ix_average_stay_length_population'), 'average_stay_length', ['population'], unique=False)
    op.create_index(op.f('ix_average_stay_length_range'), 'average_stay_length', ['range'], unique=False)
    op.create_index(op.f('ix_average_stay_length_report_id'), 'average_stay_length', ['report_id'], unique=False)
    op.create_index(op.f('ix_average_stay_length_started'), 'average_stay_length', ['started'], unique=False)
    op.create_index(op.f('ix_average_stay_length_timestamp'), 'average_stay_length', ['timestamp'], unique=False)
    op.create_index(op.f('ix_average_stay_length_uuid'), 'average_stay_length', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_average_stay_length_uuid'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_timestamp'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_started'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_report_id'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_range'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_population'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_incomplete'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_criminality'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_created_at'), table_name='average_stay_length')
    op.drop_index(op.f('ix_average_stay_length_agency'), table_name='average_stay_length')
    op.drop_table('average_stay_length')
    # ### end Alembic commands ###
